version: "3"

services:
  backend:
    restart: unless-stopped
    build:
      context: ./my-store-api
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    image: store_api_image
    container_name: store_api_container
    environment:
      FRONTEND_URL: "http://localhost:3000"
      PORT: "3030"
    networks:
      - internal
    volumes:
      - ./my-store-api:/app
      - /app/node_modules

  backend-mail:
    restart: unless-stopped
    build:
      context: ./my-store-api-mail
      dockerfile: Dockerfile
    ports:
      - "3031:3031"
    image: store_api_mail_image
    container_name: store_api_mail_container
    environment:
      ADMIN_MAIL: mystoreio368@gmail.com
    networks:
      - internal
    volumes:
      - ./my-store-api-mail:/app
      - /app/node_modules
      - /app/prisma

  frontend:
    build:
      context: ./my-store-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: store_front_image
    container_name: store_front_container
    environment:
      NEXT_PUBLIC_API_ENDPOINT: "http://backend:3030"
    networks:
      - internal
    depends_on:
      - backend
      - backend-mail
    volumes:
      - ./my-store-front:/app
      - /app/node_modules
      - /app/.next

networks:
  internal:
    name: my-store-internal
    driver: bridge
